### ISSUE TITLE
Incoherent Coding Style

### ISSUE THREAD

**Issue by sebastianriese** [OpenEIT/OpenEIT#1]
The dashboard code and the supporting modules are incoherently indented, documented and spaced (especially, they violate the recommendations of [PEP 8](https://www.python.org/dev/peps/pep-0008/)). Further the naming of the modules is not friendly for installation.

I propose the following changes:
* use coherent indentation, docstring style and spacing (ideally conforming to PEP8)
* create a package called `OpenEIT` (or `open_eit` to make pep 8 happy)
* move the support modules there and pep8ify their names (e.g. `Serialhandler` => `OpenEIT.serial_handler`)
* add a setup.py  that installs the OpenEIT package

I consider a coherent style highly relevant for the long term success of the project, since coherent style is inviting to contributors and helps with long-term maintainablity.

I'd be happy to do the changes and open a PR with the adapted code, but since it is a quite invasive procedure I wanted to ask for an okay before I started (especially since this will make merging concurrent changes difficult!).

**Comment by JeanRintoul** [comment]
Thank you for pointing this out. I didn't even consider this and agree that it would be better if it were PEP8 compliant. I'd be happy for you to make the changes if you'd like to go ahead and make a PR.
