### ISSUE TITLE
Timeseries doesn't show data until after switching to Spectroscopy tab.

### ISSUE THREAD

**Issue by DanLipsitt** [OpenEIT/OpenEIT#26]
To reproduce:

1. Connect (tested with USB).
1. Send `a` to microcontroller.
1. Switch to TimeSeries tab - the chart is blank.
1. Switch to Spectroscopy tab. The spectrogram renders and updates.
1. Switch back to TimeSeries tab. The timeseries renders and updates.

**Comment by McD-NMI** [comment]
Having a similar issue. Timeseries just doesnt render. If I go to Spectroscopy tab it doesnt necesxsarily update. Sometimes if I am lucky then I see the timeseries plot but then it disappears if I switch tabs

**Comment by JeanRintoul** [comment]
Please see video tutorial and change modes per this tutorial seen at openeit.github.io. I'd love any bug updates if anyone would like to attempt to resolve.
