### ISSUE TITLE
No EIT image shown in dashboard

### ISSUE THREAD

**Issue by FKShi** [OpenEIT/OpenEIT#30]
I use Windows and run OpenEIT wit anaconda. When I finally successfully connected the EIT kit to the dashboard (the EIT kit was connected to the electrode in the tank), no images were reconstructed, there was only a monochromatic circle on the right. It seems that the impedance measurement was not conducted at all.

![image](https://user-images.githubusercontent.com/46633395/66475377-7ffeae00-ea93-11e9-9e36-fbefb4f22ffb.png)
![0b5beb61c703f438868c06c5f904a83](https://user-images.githubusercontent.com/46633395/66475461-a7557b00-ea93-11e9-9f4d-5bffe3d7d712.jpg)

**Comment by JeanRintoul** [comment]
It looks like you have no serial connection. Each Spectra unit has been tested to ensure the COM port works before sending it out - so it's likely a config error in your serial connection. What OS are you using? Can you stream serial using real-term(skip the dashboard and just look at a serial stream)? 

Before trying to recreate an image I suggest spending enough time on the control tab to ensure you are actually streaming data. It doesn't look like the device is doing that - if it is, the data will come through on the text box of the control tab.

**Comment by credensjusticiam** [comment]
i have this same problem,.the serial connection was establshed, and the data is streamed,. but the reconstruction image is not shown, only the graphic

![eit1](https://user-images.githubusercontent.com/56707257/67061037-2c721b80-f189-11e9-8043-a192b27f155c.PNG)
![eit2](https://user-images.githubusercontent.com/56707257/67061039-2d0ab200-f189-11e9-8646-c2bdc56ef9e5.PNG)
![eit coba](https://user-images.githubusercontent.com/56707257/67061231-e4072d80-f189-11e9-8792-a0d37133e319.JPG)

**Comment by JeanRintoul** [comment]
First, take the object out of your tank so there is only water, then wait, and select 'baseline'. You should see the data update and the histogram change. Now put the object back in and wait to see an image. An easy way to see if the data is being streamed to the imaging tab is to not the histogram which shows the numerical values of the image reconstruction and their distribution. Is the histogram changing as data comes in?

**Comment by McD-NMI** [comment]
I am having the exactsame issue, on Windows 10. 

Histogram and EIT image were updating for a little bit, but then it stopped. Data is straming, but histogram and EIT no logner change.

**Comment by JeanRintoul** [comment]
Interesting. Can you give me exact steps to recreate this issue, then can look into it? 

- In the meantime, try turning the device off, then on, then reconnecting the dashboard.

**Comment by McD-NMI** [comment]
I feel like it is actually related to Issue #29. Seems to happenign when I change the # of electrodes in the imaging tab. I get the same error messages in the terminal. Perhaps it is the same for @FKShi and @credensjusticiam?

**Comment by credensjusticiam** [comment]
my problem is not solved yet, @McD-NMI ,. i've been trying @JeanRintoul suggestion, but still not working though,.right now the data is sometime streamed and sometime it is not,
to Jean @JeanRintou:l maybe you could give us video instruction how to set up the device, especially in windows based OS

**Comment by JeanRintoul** [comment]
Here is a new video walking through basic functions that takes a user from unpacking the box through to imaging. Hope it helps: [Basic Use Video Tutorial](https://youtu.be/Ssm7BgsbbWI)

Instructions to install and set up for windows can be found here: https://github.com/OpenEIT/OpenEIT 
Please take note that for Windows you will need to follow the VCP FTDI driver install outlined in these directions.

**Comment by kazib99** [comment]
@JeanRintoul I just got the device and it took me a while to set it up, but everything runs right now except I don't get the image in the screen. I sometimes get a monochromatic circle, like the one in the first comment in the thread, but most of the time I get an image like this
![Screenshot (87)](https://user-images.githubusercontent.com/45022291/88345118-47268180-cd13-11ea-8cb3-ad44a81874b6.png)

The histogram will update with the new data for a few iterations, and will then stop updating even though I can see in the terminal new data is being taken.

Any solutions to this?

**Comment by JeanRintoul** [comment]
I would say there is something wrong with the serial streaming - in which case it's worth showing that you have that set up correctly, and working. First, have you gone through this tutorial:https://youtu.be/Ssm7BgsbbWI 
Questions: 
1. What operating system are you running? 
2. Did you install the serial VCP drivers if you are running windows as per the installation readme: https://github.com/OpenEIT/OpenEIT
3. Can you see a serial stream if you open a serial streaming program like realterm? 
4. When you open the EIT Dashboard, and then connect to the serial stream on the Control tab, do you see numbers fill up in the window where it says 'streamed data'? If you do not, can you switch the power on and off the Spectra and now see it running?
5. Staying on the control tab, can you change the modes? For instance, it starts in EIT 16 electrode mode, if you type C and hit send to switch it into 8 electrode EIT mode, does it change mode and you can see new serial data streamed? 
6. After verifying correct functionality in the control tab, can you now move to the imaging tab and see the image? If not, do you get any debugging output about the error?

**Comment by JeanRintoul** [comment]
Any further questions, or troubles, please open a new issue. Otherwise, with above detailed instructions and videos I assume this issue is resolved.
