### ISSUE TITLE
Adjusting frequency

### ISSUE THREAD

**Issue by fajartimur** [OpenEIT/OpenEIT#32]
Hi Jean, 
I want to ask about certain topic, i read at this site "https://www.crowdsupply.com/mindseye-biomedical/spectra" it said that".....and electrical impedance tomography, between 80 Hz and 80 kHz, with up to 32 electrodes.". 
can you give me the instruction or tutorial how to adjust this frequency please?,.ie: i want to inject 75kHz signal (single frequency) at the phantom.
thank you

**Comment by JeanRintoul** [comment]
Adjusting the frequency can be done in firmware - please check the firmware repositories. Spectra device supports EIT(with 3 stim patterns 8,16,32 electrode), bioimpedance spectroscopy at the selected frequencies in the firmware, and time series impedance as documented in the firmware. Further developments are welcome however!

**Comment by fajartimur** [comment]
thank you for the reply,.where can i find this firmware repositories?, can you give a link please

**Comment by JeanRintoul** [comment]
here is the top level listing all the directories of the project: https://github.com/openeit 

The firmware repository is labelled EIT_firmware

**Comment by AdrienFoueillassar** [comment]
The frequency and amplitude of the injected signal are specified in the modes.h file

**Comment by JeanRintoul** [comment]
Thanks @AdrienFoueillassar
