### ISSUE TITLE
data transfer over bluetooth in Linux-Ubuntu

### ISSUE THREAD

**Issue by Guruprasad-Rao** [OpenEIT/OpenEIT#33]
Hi Jean

I installed Ubuntu 18.04.3 via virtualbox 6.0 to test the Spectra functionality using bluetooth. I bought sense bluetooth dongle and connected successfully with OS. 

Spectra was connected to Ubuntu. Python app run successfully. Server chrome page was also launched after a few restarts of OS.

But pairing did not happen. So I think the data transfer is not possible. Also in dash board of openEIT, the connect button only connects via USB. Can you please provide some information how to establish data transfer over bluetooth. OR how to communicate from dash via bluetooth when connection is there.

1 Is pairing necessary ? (If yes how to do it)

Thanks
![2](https://user-images.githubusercontent.com/37188517/67381024-8741b380-f58b-11e9-9c3d-e65ad4d41f93.png)
![1](https://user-images.githubusercontent.com/37188517/67381029-8872e080-f58b-11e9-9daa-2e6198188a59.png)
![3](https://user-images.githubusercontent.com/37188517/67381036-8a3ca400-f58b-11e9-8ff1-bece6b32587b.png)

**Comment by JeanRintoul** [comment]
this is an open todo which I'd love help with. So far I've fully tested OSX, but different librarie are needed on Ubuntu. It seems to connect but maybe it needs a bit more debugging as bluetooth is particularly finnicky on different OS's. If you want, just use the USB cable for a nice strong no questions asked UART connection.
