### ISSUE TITLE
Issue with read file - parse_line

### ISSUE THREAD

**Issue by nakulpatel2410** [OpenEIT/OpenEIT#37]
I think there is an issue with parse_any_line. I tried to read data from the dashboard and got the error code 

"
File "C:\Users\nakul\Documents\OpenEIT\OpenEIT-master\OpenEIT\dashboard\controller.py", line 86, in __init__
    data = OpenEIT.backend.parse_line(line)
AttributeError: module 'OpenEIT.backend' has no attribute 'parse_line'
"

I looked through the history of the backend code and saw that parse_line has been updated to parse_any_line. I was wondering if anyone else had come across this issue and if there was a simple fix to resolve it. I think I traced the issue to controller.py-line 86 (see screenshot) where it still calls the old version of the code.

I am a student working on an EIT project to detect muscle contractions of the human stomach. I am still learning to use python and any help would be useful.

![issue](https://user-images.githubusercontent.com/63193767/90214803-c0fee600-de4d-11ea-85cf-09f4de20e3f4.png)

**Comment by JeanRintoul** [comment]
A previous version of this code used an earlier library, which is why it changed from parse_line to parse_any_line. Would you be able to compare the precise versions of dash/plotly you have with the requirements document, and confirm that the version numbers match?

**Comment by nakulpatel2410** [comment]
Hey Jean thanks for the reply. I have just checked the versions of dash/plotly with the requirements document, and they seem to be the exact same.

**Comment by JeanRintoul** [comment]
Would you be able to give step by step instructions to recreate this error?

**Comment by sam-richardson** [comment]
I think you probably want controller.py-line 86 to read:

data = OpenEIT.backend.serialhandler.parse_any_line(line,'b')

**Comment by JeanRintoul** [comment]
Thx - fixed.
