### ISSUE TITLE
mesh reconstruction image from offline.py

### ISSUE THREAD

**Issue by ajkh624** [OpenEIT/OpenEIT#39]
HI.
I really want to generate mesh reconstruction image from 'raw data.txt' that I download from dash board or 'simdata.txt' from simdata.py. Could you show us a demonstration how to generate reconstruction images from simdata.txt using offline.py? 
When I activate offline.py, it mentioned 'lungwgel.bin' missing. If you have a 'lungwgel.bin' file, could you share for me? 

![Figure_1](https://user-images.githubusercontent.com/59854050/91780452-99bc5d00-ec32-11ea-8aee-5610eb33b47d.png)

this is an image I generate from 'simdata' from 'offline.py' .

**Comment by JeanRintoul** [comment]
Hello, I think you should replace lungwgel.bin with your own data file. You can create a data file as well through simdata.py and an example is checked in and named simdata.txt. I will update with more info when I get time.

**Comment by ajkh624** [comment]
I did replace lungwgel.bin with my data file. Here is my data file(rawdata8.txt) and offline_0902.py I ran. 
I used Greit 32 algorithm. Please would you run this if you have a free time? Thank you.

[offline_0902.zip](https://github.com/OpenEIT/OpenEIT/files/5159733/offline_0902.zip)

**Comment by JeanRintoul** [comment]
Hello, I just did an update to offline.py to make it more clear. Please give it another go. Another issue is that simdata.txt appends data to the simdata.txt file, so if you change your EIT parameters(i.e. electrode number), it will have data in two different formats- just something to watch out for. 

Here is a reconstructed tomographic image of the datafile you provided using offline.py 
<img width="658" alt="rawdata8_image_output" src="https://user-images.githubusercontent.com/315476/91992706-5cd49100-ed2c-11ea-9d8c-4a66d12569c4.png">

This new update works for me. Happy to answer any other questions.
